# This is a default properties file for the Playwright test framework.
# You can override these properties by creating a custom properties file and specifying its path using the -Dconfig.file command line argument when running your tests.

# Application URL to be tested
APP_URL=https://www.saucedemo.com/

# Supported browser types: Firefox, Webkit, Chromium
DEFAULT_BROWSER=chromium

# Default is true for Playwright, set to false to run tests in headless mode
HEADLESS=false

# Default timeout in Playwright for waiting for elements is 30 seconds
TIMEOUT=15